# Hardware configuration for 2018 Mac Mini with T2 chip
# This is a placeholder that should be regenerated after installation
# with: nixos-generate-config --root /mnt
#
# Key hardware:
# - CPU: Intel Core i7-8700B (Coffee Lake, 6-core)
# - GPU: Intel UHD Graphics 630 (supports Quick Sync Video)
# - Security: Apple T2 chip (requires special kernel/drivers)
# - Storage: Internal NVMe SSD (via T2 controller)
# - Network: Gigabit Ethernet + WiFi (WiFi disabled for server use)
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
    initrd = {
      # Network driver for Ethernet (Intel I219-LM on Mac Mini 2018)
      # Exact driver name will be confirmed after installation
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme" # T2-controlled NVMe SSD
        "usbhid"
        "usb_storage"
        "sd_mod"
        "thunderbolt" # Thunderbolt 3 ports
        "e1000e" # Intel Gigabit Ethernet (common on Mac Mini)
      ];
      kernelModules = [];
      # Note: LUKS encryption is optional for plex server
      # Uncomment if using full disk encryption:
      # luks = {
      #   reusePassphrases = true;
      #   devices."cryptroot" = {
      #     device = "/dev/nvme0n1p2";
      #     allowDiscards = true;
      #   };
      # };
    };

    # Enable Intel GuC for better Quick Sync performance
    # GuC enables low-power encoding modes beneficial for transcoding
    kernelParams = ["i915.enable_guc=2"];
  };

  # Filesystem layout - will be regenerated by nixos-generate-config
  # This layout assumes no encryption for simplicity on a home media server
  fileSystems = {
    "/" = {
      device = "none";
      fsType = "tmpfs";
      options = ["defaults" "size=8G" "mode=0755"];
    };
    "/boot" = {
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
      options = ["umask=0077"];
    };
    "/nix" = {
      device = "/dev/disk/by-label/nix";
      fsType = "ext4";
    };
  };

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Intel CPU microcode updates
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
